import {
  FaBriefcase,
  FaUserTie,
  FaMoneyBill,
  FaChartLine,
  FaClipboardList,
  FaCheck,
  FaUtensils,
  FaCoffee,
  FaPizzaSlice,
  FaShoppingCart,
  FaCar,
  FaHome,
  FaPlane,
  FaHospital,
  FaGraduationCap,
  FaMusic,
  FaBook,
  FaCamera,
  FaPaintBrush,
  FaGamepad,
  FaUsers,
  FaUserFriends,
  FaCalendarAlt,
  FaExclamationCircle,
  FaFileAlt,
  FaHeart,
  FaClock,
  FaHamburger,
} from 'react-icons/fa';
import { IoIosBriefcase, IoIosPaper, IoIosStats, IoIosRestaurant, IoIosSubway } from 'react-icons/io';
import {
  MdWork,
  MdBusinessCenter,
  MdAssignment,
  MdLocalCafe,
  MdLocalPizza,
  MdLocalShipping,
  MdLocalGroceryStore,
  MdHotel,
  MdSchool,
  MdMusicNote,
  MdLocalLibrary,
  MdPhotoCamera,
  MdBrush,
  MdVideogameAsset,
  MdPeople,
  MdNotifications,
  MdThumbUp,
  MdAlarm,
} from 'react-icons/md';

const taskIcons = [
  {
    nome: 'Trabalho',
    icones: [
      { nome: 'Maleta', icone: FaBriefcase },
      { nome: 'Gravata', icone: FaUserTie },
      { nome: 'Dinheiro', icone: FaMoneyBill },
      { nome: 'Gráfico', icone: FaChartLine },
      { nome: 'Tarefas', icone: FaClipboardList },
      { nome: 'Maleta', icone: IoIosBriefcase },
      { nome: 'Papel', icone: IoIosPaper },
      { nome: 'Estatísticas', icone: IoIosStats },
      { nome: 'Trabalho', icone: MdWork },
    ],
  },
  {
    nome: 'Comida',
    icones: [
      { nome: 'Utensílios', icone: FaUtensils },
      { nome: 'Café', icone: FaCoffee },
      { nome: 'Lanche', icone: FaHamburger  },
      { nome: 'Restaurante', icone: IoIosRestaurant },
      { nome: 'Café ', icone: MdLocalCafe },
      { nome: 'Pizza ', icone: MdLocalPizza },
    ],
  },
  {
    nome: 'Serviço',
    icones: [
      { nome: 'Compras', icone: FaShoppingCart },
      { nome: 'Carro', icone: FaCar },
      { nome: 'Casa', icone: FaHome },
      { nome: 'Avião', icone: FaPlane },
      { nome: 'Hospital', icone: FaHospital },
      { nome: 'Entrega ', icone: MdLocalShipping },
      { nome: 'Mercado ', icone: MdLocalGroceryStore },
      { nome: 'Hotel ', icone: MdHotel },
    ],
  },
  {
nome: 'Diversos',
icones: [
{ nome: 'Tarefa', icone: MdAssignment },
{ nome: 'Verificado', icone: FaCheck },
{ nome: 'Formatura', icone: FaGraduationCap },
{ nome: 'Música', icone: FaMusic },
{ nome: 'Livro', icone: FaBook },
{ nome: 'Câmera', icone: FaCamera },
{ nome: 'Câmera ', icone: MdPhotoCamera },
{ nome: 'Pincel', icone: FaPaintBrush },
{ nome: 'Pincel ', icone: MdBrush },
{ nome: 'Jogo ', icone: MdVideogameAsset },
],
},
{
nome: 'Social',
icones: [
{ nome: 'Usuários', icone: FaUsers },
{ nome: 'Amigos', icone: FaUserFriends },
{ nome: 'Pessoas ', icone: MdPeople },
],
},
{
nome: 'Lembrete',
icones: [
{ nome: 'Calendário', icone: FaCalendarAlt },
{ nome: 'Urgente', icone: FaExclamationCircle },
{ nome: 'Arquivo', icone: FaFileAlt },
{ nome: 'Coração', icone: FaHeart },
{ nome: 'Relógio', icone: FaClock },
{ nome: 'Notificações', icone: MdNotifications },
{ nome: 'Curtir', icone: MdThumbUp },
{ nome: 'Alarme', icone: MdAlarm },
],
},
];

export default taskIcons;